import"./assets/styles-JE8YjOlG.js";import{a as r,i as c}from"./assets/vendor-4yCzdkXl.js";const y="https://dummyjson.com/",a={CATEGORIES:"products/category-list",PRODUCTS:"products",BY_CATEGORY:"products/category/",SEARCH_FORM:"products/search"};r.defaults.baseURL=y;const _=async()=>{const{data:t}=await r(`${a.CATEGORIES}`);return t},i=async t=>{const{data:e}=await r(`${a.PRODUCTS}`,{params:{limit:12,skip:(t-1)*12}});return e},f=async t=>{const{data:e}=await r(`${a.BY_CATEGORY}${t}`);return e},h=async t=>{const{data:e}=await r(`${a.SEARCH_FORM}`,{params:{q:t}});return e},o={categoryList:document.querySelector(".categories"),productList:document.querySelector(".products"),divNotFound:document.querySelector(".not-found"),form:document.querySelector(".search-form")},L=t=>{const e=t.map(s=>`<li class="categories__item">
   <button class="categories__btn" type="button">${s}</button>
 </li>`).join("");o.categoryList.innerHTML=e},n=t=>{const e=t.map(({id:s,thumbnail:d,tags:l,title:u,brand:g,category:p,price:m})=>`<li class="products__item" data-id="${s}">
    <img class="products__image" src="${d}" alt="${l}"/>
    <p class="products__title">${u}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${g}</span></p>
    <p class="products__category">Category: ${p}</p>
    <p class="products__price">Price: ${m}$</p>
 </li>
`).join("");o.productList.insertAdjacentHTML("beforeend",e)},b=()=>{o.productList.innerHTML=""},v=()=>{const t=document.querySelector(".categories__btn");t&&t.classList.add("categories__btn--active")},w=t=>{document.querySelectorAll(".categories__btn--active").forEach(s=>s.classList.remove("categories__btn--active")),t.classList.add("categories__btn--active")},S=async()=>{try{const t=await _();L(["All",...t]),v()}catch(t){console.log(t),c.error({message:"Oops, something went wrong!"})}},C=async()=>{try{const{products:t}=await i(1);n(t)}catch(t){console.log(t),c.error({message:"Oops, something went wrong!"})}},B=async t=>{if(t.target.nodeName!=="BUTTON")return;const e=t.target.textContent;b(),w(t.target),o.divNotFound.classList.remove("not-found--visible");try{if(e==="All"){const{products:s}=await i(1);n(s)}else{const{products:s}=await f(e);s.length===0&&o.divNotFound.classList.add("not-found--visible"),n(s)}}catch(s){console.log(s)}},$=async t=>{t.preventDefault();const e=t.target.elements.searchValue.value.trim();if(e===""){c.warning({message:"enter something for search"});return}try{const s=await h(e);console.log(s)}catch(s){console.log(s),c.error({message:"Oops, something went wrong!"})}};S();C();o.categoryList.addEventListener("click",B);o.form.addEventListener("submit",$);
//# sourceMappingURL=index.js.map
