import"./assets/styles-JE8YjOlG.js";import{a as c,i as n}from"./assets/vendor-4yCzdkXl.js";const m="https://dummyjson.com/",a={CATEGORIES:"products/category-list",PRODUCTS:"products",BY_CATEGORY:"products/category/"};c.defaults.baseURL=m;const y=async()=>{const{data:t}=await c(`${a.CATEGORIES}`);return t},i=async t=>{const{data:o}=await c(`${a.PRODUCTS}`,{params:{limit:12,skip:(t-1)*12}});return o},L=async t=>{const{data:o}=await c(`${a.BY_CATEGORY}${t}`);return o},e={categoryList:document.querySelector(".categories"),productList:document.querySelector(".products"),divNotFound:document.querySelector(".not-found")},b=t=>{const o=t.map(s=>`<li class="categories__item">
   <button class="categories__btn" type="button">${s}</button>
 </li>`).join("");e.categoryList.innerHTML=o},r=t=>{const o=t.map(({id:s,thumbnail:d,tags:l,title:u,brand:p,category:g,price:_})=>`<li class="products__item" data-id="${s}">
    <img class="products__image" src="${d}" alt="${l}"/>
    <p class="products__title">${u}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${p}</span></p>
    <p class="products__category">Category: ${g}</p>
    <p class="products__price">Price: ${_}$</p>
 </li>
`).join("");e.productList.insertAdjacentHTML("beforeend",o)},f=()=>{e.productList.innerHTML=""},v=()=>{const t=document.querySelector(".categories__btn");t&&t.classList.add("categories__btn--active")},C=t=>{document.querySelectorAll(".categories__btn--active").forEach(s=>s.classList.remove("categories__btn--active")),t.classList.add("categories__btn--active")},T=async()=>{try{const t=await y();b(["All",...t]),v()}catch(t){console.log(t),n.error({message:"Oops, something went wrong!"})}},$=async()=>{try{const{products:t}=await i(1);r(t)}catch(t){console.log(t),n.error({message:"Oops, something went wrong!"})}},h=async t=>{if(t.target.nodeName!=="BUTTON")return;const o=t.target.textContent;f(),C(t.target),e.divNotFound.classList.remove("not-found--visible");try{if(o==="All"){const{products:s}=await i(1);r(s)}else{const{products:s}=await L(o);s.length===0&&e.divNotFound.classList.add("not-found--visible"),r(s)}}catch(s){console.log(s)}};T();$();e.categoryList.addEventListener("click",h);
//# sourceMappingURL=index.js.map
